//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancol_PTM.libDatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectTask : IValidatableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTask()
        {
            this.ManagerComments = new HashSet<ManagerComment>();
        }
        
        public System.Guid Id { get; set; }
        [DisplayName("Employeed ID")]
        
        public Nullable<System.Guid> Employeeid { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Task Start Date")]
        [Required(ErrorMessage = "Field is required")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Task End Date")]
        [Required(ErrorMessage = "Field is required")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> TaskEndDate { get; set; }
        [Required(ErrorMessage = "Field is required")]
        [DisplayName("Task Status ID")]
        public Nullable<System.Guid> TaskStatusid { get; set; }
        [Required(ErrorMessage = "Field is required")]
        [DisplayName("User Story ID")]
        public Nullable<System.Guid> UserStoryid { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> InsAt { get; set; }
        public string InsBy { get; set; }
        public Nullable<System.DateTime> UpdAt { get; set; }
        public string UpdBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerComment> ManagerComments { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual UserStory UserStory { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (TaskStartDate > TaskEndDate)
            {
                yield return new ValidationResult("Endate must be greater than startdate");
            }
        }
    }
}
