//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancol_PTM.libDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserStory()
        {
            this.ProjectTasks = new HashSet<ProjectTask>();
        }
    
        public System.Guid Id { get; set; }
        public string Story { get; set; }
        public Nullable<System.Guid> Projectid { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> InsAt { get; set; }
        public string InsBy { get; set; }
        public Nullable<System.DateTime> UpdAt { get; set; }
        public string UpdBy { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
    }
}
